# Generated by Django 3.1.7 on 2021-07-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20210701_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
